__app_name__ = "mimicbot"
__version__ = "0.0.1"

(
    SUCCESS,
    UNKNOWN_ERROR,
    DIR_ERROR,
    FILE_ERROR,
    API_KEY_ERROR,
    PRIVILAGES_ERROR,
    BOT_ERROR,
    MISSING_GUILD_ERROR,
    USER_NAME_ERROR,
    ABORT,
) = range(10)

ERROR = {
    SUCCESS: "SUCCESS",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    DIR_ERROR: "DIR_ERROR",
    FILE_ERROR: "FILE_ERROR",
    API_KEY_ERROR: "API_KEY_ERROR",
    PRIVILAGES_ERROR: "PRIVILAGES_ERROR",
    BOT_ERROR: "BOT_ERROR",
    MISSING_GUILD_ERROR: "MISSING_GUILD_ERROR",
    USER_NAME_ERROR: "USER_NAME_ERROR",
    ABORT: "ABORT",
}
